esphome:
  name: esp8266-relay

esp8266:
  board: nodemcuv2
  framework:
    version: recommended

# Enable logging
logger:
  level: INFO

# MQTT Configuration
mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_password

# OTA Updates
ota:
  - platform: esphome
    password: !secret ota_password

# WiFi Configuration with Soft AP Fallback
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (soft AP) when WiFi connection fails
  ap:
    ssid: "ESP8266-Relay Fallback"
    password: "12345678"

# Captive portal for easy configuration when in AP mode
captive_portal:

# Relay Switch on GPIO4
switch:
  - platform: gpio
    pin: GPIO4
    name: "Relay"
    id: relay_1
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - logger.log: "Relay turned ON"
    on_turn_off:
      - logger.log: "Relay turned OFF"
