esphome:
  name: pms-air-quality-esp8266
  
esp8266:
  board: d1_mini
  framework:
    version: recommended

# Enable logging
logger:
  level: INFO
  # Lower the UART log level to avoid flooding logs with sensor data
  logs:
    sensor: INFO
    pmsx003: INFO

# MQTT Configuration
mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

# OTA Updates
ota:
  - platform: esphome
    password: !secret ota_password

# WiFi Configuration with Soft AP Fallback
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (soft AP) when WiFi connection fails
  ap:
    ssid: "PMS-AirQuality Fallback"
    password: "12345678"

# Captive portal for easy configuration when in AP mode
captive_portal:

# UART Configuration for PMS sensor
# PMS5003 uses UART: TX on GPIO1 (TX), RX on GPIO3 (RX)
# For other boards, you can use different pins:
# - ESP8266: GPIO13 (RX), GPIO15 (TX)
# - ESP32: GPIO16 (RX), GPIO17 (TX)
uart:
  rx_pin: GPIO3  # Connect to PMS TX pin
  tx_pin: GPIO1  # Connect to PMS RX pin
  baud_rate: 9600

# PMS Air Quality Sensor
# Supports PMS5003, PMS7003, PMS1003, PMSA003
sensor:
  - platform: pmsx003
    type: PMSX003  # Change to PMS5003T for temperature/humidity variant
    # PM2.5 - Fine particulate matter (most important for health)
    pm_2_5:
      name: "PM2.5"
      id: pm25
      unit_of_measurement: "µg/m³"
      icon: "mdi:air-filter"
      on_value:
        then:
          - logger.log:
              format: "PM2.5: %.1f µg/m³"
              args: ['x']
    
    # PM1.0 - Ultra-fine particles
    pm_1_0:
      name: "PM1.0"
      id: pm10
      unit_of_measurement: "µg/m³"
      icon: "mdi:air-filter"
    
    # PM10.0 - Coarse particulate matter
    pm_10_0:
      name: "PM10.0"
      id: pm100
      unit_of_measurement: "µg/m³"
      icon: "mdi:air-filter"
    
    # Update interval
    update_interval: 60s

  # WiFi Signal Strength
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  # Uptime Sensor
  - platform: uptime
    name: "Uptime"
    update_interval: 60s

# Text Sensors for additional information
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    mac_address:
      name: "MAC Address"

  - platform: version
    name: "ESPHome Version"

# Binary sensor to show connection status
binary_sensor:
  - platform: status
    name: "Status"

# Optional: Button to restart the device remotely
button:
  - platform: restart
    name: "Restart"
