esphome:
  name: wiat-ld2410

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO

ld2410:
  uart_id: ld2410_uart
  throttle: 300ms
  id: ld2410_comp

mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_password

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wiat Ld2410 Fallback Hotspot"
    password: !secret ap_password

captive_portal:

uart:
  id: ld2410_uart
  tx_pin: GPIO18
  rx_pin: GPIO33
  baud_rate: 256000
  parity: NONE
  stop_bits: 1


binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    out_pin_presence_status:
      name: out pin presence status

# sensor:
#   - platform: ld2410
#     light:
#       name: light
#     moving_distance:
#       name : Moving Distance
#     still_distance:
#       name: Still Distance
#     moving_energy:
#       name: Move Energy
#     still_energy:
#       name: Still Energy
#     detection_distance:
#       name: Detection Distance
#     g0:
#       move_energy:
#         name: g0 move energy
#       still_energy:
#         name: g0 still energy
#     g1:
#       move_energy:
#         name: g1 move energy
#       still_energy:
#         name: g1 still energy
#     g2:
#       move_energy:
#         name: g2 move energy
#       still_energy:
#         name: g2 still energy
#     g3:
#       move_energy:
#         name: g3 move energy
#       still_energy:
#         name: g3 still energy
#     g4:
#       move_energy:
#         name: g4 move energy
#       still_energy:
#         name: g4 still energy
#     g5:
#       move_energy:
#         name: g5 move energy
#       still_energy:
#         name: g5 still energy
#     g6:
#       move_energy:
#         name: g6 move energy
#       still_energy:
#         name: g6 still energy
#     g7:
#       move_energy:
#         name: g7 move energy
#       still_energy:
#         name: g7 still energy
#     g8:
#       move_energy:
#         name: g8 move energy
#       still_energy:
#         name: g8 still energy
    